### ISSUE TITLE
Tagged Releases?

### ISSUE THREAD

**Issue by okal** [onaio/hatti#37]
Would make it easier to go back to a known state of the codebase. Difficult as things stand now, with merges and all that, when working with checkouts/snapshots.

**Comment by prabhasp** [comment]
Agree, and glad that we now have [releases](https://github.com/onaio/hatti/releases).
Ideally, we should also release non-snapshot versions. For the moment, that is blocked by the inclusion of c2, since we need the latest version of c2, a SNAPSHOT version, and non-snapshot releases cannot have SNAPSHOT dependencies.

**Comment by pld** [comment]
to summarize the slack discussion that closes this

1. we'll do at least weekly release when there are changes, the current snapshot will be changed to a release
2. all releases get tagged
3. after a release/tag we bump the version to a snapshot for changes

and, when in doubt prefer a new release, multiple per week is entirely fine
